### ISSUE TITLE
GRIDCRO2D

### ISSUE THREAD

**Issue by leoand23** [mmb-carb/ESTA#9]
Why do we have this file? can we replace it or create it on the fly?

**Comment by john-science** [comment]
Okay, so I found out some interesting things by looking at the old code.  We originally needed the `GRIDCO2D` file because we were reading in the ITN road networks and generating spatial surrogates on the fly, much like DTIM did.

But for the newer spatial surrogate approach we do not need the `GRIDCRO2D` file, all we need is a string that says "4km" or "1km", or whatever.

So my current recommendation, at the very least, is to change the non-ITN run scripts to just not use take a `GRIDCRO2D` parameter, but instead a `grid_scale` parameter with the string we need.

Perhaps we should also re-visit if we want to suppport the ITN/DTIM-like functionality forever, or if that was only useful for the initial testing.
